---
- name: Webserver playbook
  hosts: ansibleclient

  tasks:
    - name: Package installation
      yum: name=httpd state=present
     
    - name: Amending webserver configuration file
      copy: dest=/var/www/html/index.html content="This is my GitHub File"
     
    - name: Starting web services
      service: name=httpd state=started
    
    - name: package installation
      yum: name=telnet state=present
...

